# Site settings
name: Victoria Lynn Hardy
email: vlhardy22@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Quality Assurance, Manual Testing, Java, Performance Testing, Regression, Remote Work, Agile"
skills: "Mid level Quality Assurance Engineer in Pawtucket, RI"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/victorialhardy/
 # - title: medium
 #   url: https://medium.com/@cgroom
  - title: twitter
    url: https://twitter.com/vl_hardy
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 800080
  primary-rgb: "128,0,128"
  secondary: C433FF
  secondary-dark: FF33E3
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
